// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADivc4sXGp1qC6r9jUvBJDwAr9pBOnnvI',
    appId: '1:534169808092:web:782fd709ce5ac4e5c25819',
    messagingSenderId: '534169808092',
    projectId: 'flutter-reddit-clone-8bb54',
    authDomain: 'flutter-reddit-clone-8bb54.firebaseapp.com',
    storageBucket: 'flutter-reddit-clone-8bb54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADivc4sXGp1qC6r9jUvBJDwAr9pBOnnvI',
    appId: '1:534169808092:android:cec6dc6825948382c25819',
    messagingSenderId: '534169808092',
    projectId: 'flutter-reddit-clone-8bb54',
    storageBucket: 'flutter-reddit-clone-8bb54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADivc4sXGp1qC6r9jUvBJDwAr9pBOnnvI',
    appId: '1:534169808092:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '534169808092',
    projectId: 'flutter-reddit-clone-8bb54',
    storageBucket: 'flutter-reddit-clone-8bb54.firebasestorage.app',
    iosClientId: '534169808092-YOUR_IOS_CLIENT_ID.apps.googleusercontent.com',
    iosBundleId: 'com.whatsup.app',
  );
}
